"use client";

import {
  Ban,
  CheckCircle2,
  Circle,
  Clock,
  Download,
  Eye,
  FilePlus2,
  History,
  type LucideIcon,
  PenLine,
  RotateCw,
  Send,
  Sparkles,
} from "lucide-react";

import { EmptyState } from "@/components/ui/empty-state";
import type {
  ApiAuditEntry,
  ApiDocumentRecipient,
} from "@/lib/api-types";
import { cn } from "@/lib/utils";

/**
 * Visual mapping per audit EventType. We deliberately keep the surface
 * area narrow: an icon, a label, and a Tailwind tone string that picks
 * matching foreground/background tokens. Any unknown event type falls
 * back to a neutral muted style so a future enum value never crashes
 * the timeline.
 */
type EventVisual = {
  icon: LucideIcon;
  label: string;
  /** Tailwind class string applied to the icon chip. */
  tone: string;
};

const EVENT_VISUALS: Record<string, EventVisual> = {
  DOCUMENT_CREATED: {
    icon: FilePlus2,
    label: "Document created",
    tone: "bg-primary/10 text-primary",
  },
  DOCUMENT_SENT: {
    icon: Send,
    label: "Sent for signature",
    tone: "bg-info/15 text-info",
  },
  DOCUMENT_VIEWED: {
    icon: Eye,
    label: "Opened by recipient",
    tone: "bg-muted text-muted-foreground",
  },
  DOCUMENT_FIELD_FILLED: {
    icon: PenLine,
    label: "Field filled",
    tone: "bg-info/15 text-info",
  },
  DOCUMENT_SIGNED: {
    icon: CheckCircle2,
    label: "Signed by recipient",
    tone: "bg-success/15 text-success",
  },
  DOCUMENT_RESENT: {
    icon: RotateCw,
    label: "Invitation resent",
    tone: "bg-warning/20 text-warning-foreground",
  },
  DOCUMENT_VOIDED: {
    icon: Ban,
    label: "Document voided",
    tone: "bg-destructive/10 text-destructive",
  },
  DOCUMENT_EXPIRED: {
    icon: Clock,
    label: "Signing link expired",
    tone: "bg-destructive/10 text-destructive",
  },
  DOCUMENT_DOWNLOADED: {
    icon: Download,
    label: "Downloaded",
    tone: "bg-muted text-muted-foreground",
  },
  AI_FIELDS_DETECTED: {
    icon: Sparkles,
    label: "Fields detected by AI",
    tone: "bg-primary/10 text-primary",
  },
  AI_SUMMARY_GENERATED: {
    icon: Sparkles,
    label: "Summary generated by AI",
    tone: "bg-primary/10 text-primary",
  },
};

const FALLBACK_VISUAL: EventVisual = {
  icon: Circle,
  label: "Activity",
  tone: "bg-muted text-muted-foreground",
};

/**
 * Full local datetime for an audit entry. Audit trails are precision
 * artifacts — "2 minutes ago" drifts out of usefulness the moment the
 * clinician stops looking, and it also hides the exact second two
 * events happened. We render one absolute line with the zone
 * abbreviation (e.g. "Apr 22, 2026, 1:30:29 AM PDT") so cross-timezone
 * reviews (e.g. a compliance request from another region) stay
 * unambiguous. Falls back cleanly if Intl rejects the locale/zone.
 */
const ABSOLUTE_FORMAT: Intl.DateTimeFormatOptions = {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "2-digit",
  second: "2-digit",
  hour12: true,
  timeZoneName: "short",
};

function formatAbsoluteLocal(date: Date): string {
  if (Number.isNaN(date.getTime())) {
    return "—";
  }
  try {
    return new Intl.DateTimeFormat(undefined, ABSOLUTE_FORMAT).format(date);
  } catch {
    return date.toLocaleString();
  }
}

/**
 * Best-effort actor display. We don't have a user-name lookup on the
 * client (only the recipient is exposed via doc.recipients), so we
 * return a generic role label for providers and the recipient's name
 * when we have it. SYSTEM events show "System".
 */
function actorDisplay(
  entry: ApiAuditEntry,
  recipient: ApiDocumentRecipient | null
): string {
  if (entry.actorType === "RECIPIENT") {
    return recipient?.name ?? "Recipient";
  }
  if (entry.actorType === "PROVIDER") {
    return "Clinician";
  }
  return "System";
}

/**
 * Pulls the most useful piece of metadata for each event so the entry
 * isn't just "Sent for signature — Clinician" with no context. Keeps
 * the contract permissive: metadata is JSON, the API never validates
 * its shape, so we treat each property as optional.
 */
function metadataDetail(entry: ApiAuditEntry): string | null {
  if (typeof entry.metadata !== "object" || entry.metadata === null) {
    return null;
  }
  const meta = entry.metadata as Record<string, unknown>;
  const email = typeof meta.recipientEmail === "string" ? meta.recipientEmail : null;
  const title = typeof meta.title === "string" ? meta.title : null;
  switch (entry.eventType) {
    case "DOCUMENT_SENT":
    case "DOCUMENT_RESENT":
    case "DOCUMENT_SIGNED":
      return email;
    case "DOCUMENT_CREATED":
      return title;
    default:
      return null;
  }
}

interface DocumentActivityTimelineProps {
  entries: ApiAuditEntry[];
  /** Used to resolve recipient-side actor names. */
  recipient: ApiDocumentRecipient | null;
  className?: string;
}

export function DocumentActivityTimeline({
  entries,
  recipient,
  className,
}: DocumentActivityTimelineProps): JSX.Element {
  if (entries.length === 0) {
    return (
      <EmptyState
        icon={History}
        title="No activity yet"
        description="Activity from creating, sending, viewing, and signing this document will appear here."
      />
    );
  }

  return (
    <ol
      className={cn("relative space-y-6", className)}
      aria-label="Document activity timeline"
    >
      {entries.map((entry, index) => {
        const visual = EVENT_VISUALS[entry.eventType] ?? FALLBACK_VISUAL;
        const Icon = visual.icon;
        const detail = metadataDetail(entry);
        const isLast = index === entries.length - 1;
        const absolute = new Date(entry.timestamp);
        return (
          <li key={entry.id} className="relative flex gap-4">
            {!isLast ? (
              <span
                aria-hidden="true"
                className="bg-border absolute left-5 top-10 h-[calc(100%+0.5rem)] w-px"
              />
            ) : null}
            <span
              className={cn(
                "relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full",
                visual.tone
              )}
            >
              <Icon className="h-5 w-5" strokeWidth={1.5} aria-hidden="true" />
            </span>
            <div className="min-w-0 flex-1 pb-1">
              <p className="text-body text-foreground font-medium">
                {visual.label}
              </p>
              <p className="text-body-sm text-muted-foreground mt-0.5">
                {actorDisplay(entry, recipient)}
                {detail ? (
                  <>
                    <span className="px-1.5">·</span>
                    <span className="text-foreground/70">{detail}</span>
                  </>
                ) : null}
              </p>
              <time
                dateTime={absolute.toISOString()}
                title={absolute.toISOString()}
                className="text-caption text-muted-foreground mt-1 block tabular-nums"
              >
                {formatAbsoluteLocal(absolute)}
              </time>
            </div>
          </li>
        );
      })}
    </ol>
  );
}
